"""updating the academic history model

Revision ID: 16c297932726
Revises: 8ec69bd9c6a8
Create Date: 2025-01-20 11:22:05.050755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c297932726'
down_revision: Union[str, None] = '8ec69bd9c6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_academic_history', sa.Column('subject1', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol1', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject2', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol2', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject3', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol3', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject4', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol4', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject5', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol5', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject6', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol6', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject7', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol7', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject8', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol8', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject9', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol9', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject10', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol10', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject11', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol11', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject12', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol12', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject13', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol13', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('subject14', sa.String(), nullable=True))
    op.add_column('student_academic_history', sa.Column('symbol14', sa.String(), nullable=True))
    op.drop_column('student_academic_history', 'results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_academic_history', sa.Column('results', sa.VARCHAR(), nullable=True))
    op.drop_column('student_academic_history', 'symbol14')
    op.drop_column('student_academic_history', 'subject14')
    op.drop_column('student_academic_history', 'symbol13')
    op.drop_column('student_academic_history', 'subject13')
    op.drop_column('student_academic_history', 'symbol12')
    op.drop_column('student_academic_history', 'subject12')
    op.drop_column('student_academic_history', 'symbol11')
    op.drop_column('student_academic_history', 'subject11')
    op.drop_column('student_academic_history', 'symbol10')
    op.drop_column('student_academic_history', 'subject10')
    op.drop_column('student_academic_history', 'symbol9')
    op.drop_column('student_academic_history', 'subject9')
    op.drop_column('student_academic_history', 'symbol8')
    op.drop_column('student_academic_history', 'subject8')
    op.drop_column('student_academic_history', 'symbol7')
    op.drop_column('student_academic_history', 'subject7')
    op.drop_column('student_academic_history', 'symbol6')
    op.drop_column('student_academic_history', 'subject6')
    op.drop_column('student_academic_history', 'symbol5')
    op.drop_column('student_academic_history', 'subject5')
    op.drop_column('student_academic_history', 'symbol4')
    op.drop_column('student_academic_history', 'subject4')
    op.drop_column('student_academic_history', 'symbol3')
    op.drop_column('student_academic_history', 'subject3')
    op.drop_column('student_academic_history', 'symbol2')
    op.drop_column('student_academic_history', 'subject2')
    op.drop_column('student_academic_history', 'symbol1')
    op.drop_column('student_academic_history', 'subject1')
    # ### end Alembic commands ###
