"""update subject combination

Revision ID: 4ed9d71fcd23
Revises: 922c3df86617
Create Date: 2025-01-18 16:07:11.946151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed9d71fcd23'
down_revision: Union[str, None] = '922c3df86617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_combination', sa.Column('subject1_option2', sa.String(), nullable=True))
    op.add_column('subject_combination', sa.Column('subject2_option2', sa.String(), nullable=True))
    op.add_column('subject_combination', sa.Column('subject3_option2', sa.String(), nullable=True))
    op.add_column('subject_combination', sa.Column('subject1_option3', sa.String(), nullable=True))
    op.add_column('subject_combination', sa.Column('subject2_option3', sa.String(), nullable=True))
    op.add_column('subject_combination', sa.Column('subject3_option3', sa.String(), nullable=True))
    op.add_column('subject_combination', sa.Column('subject_combination_state', sa.String(), nullable=True))
    op.add_column('subject_combination', sa.Column('suggested_subject1', sa.String(), nullable=True))
    op.add_column('subject_combination', sa.Column('suggested_subject2', sa.String(), nullable=True))
    op.add_column('subject_combination', sa.Column('suggested_subject3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_combination', 'suggested_subject3')
    op.drop_column('subject_combination', 'suggested_subject2')
    op.drop_column('subject_combination', 'suggested_subject1')
    op.drop_column('subject_combination', 'subject_combination_state')
    op.drop_column('subject_combination', 'subject3_option3')
    op.drop_column('subject_combination', 'subject2_option3')
    op.drop_column('subject_combination', 'subject1_option3')
    op.drop_column('subject_combination', 'subject3_option2')
    op.drop_column('subject_combination', 'subject2_option2')
    op.drop_column('subject_combination', 'subject1_option2')
    # ### end Alembic commands ###
