"""Add dob, gender, and address fields to Student model

Revision ID: 9edc2df59246
Revises: fe5f3f261e50
Create Date: 2025-01-17 23:42:53.103662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9edc2df59246'
down_revision: Union[str, None] = 'fe5f3f261e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_email', table_name='student')
    op.drop_index('ix_student_id', table_name='student')
    op.drop_index('ix_student_name', table_name='student')
    op.drop_index('ix_student_whatsapp_number', table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('whatsapp_number', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_whatsapp_number', 'student', ['whatsapp_number'], unique=1)
    op.create_index('ix_student_name', 'student', ['name'], unique=False)
    op.create_index('ix_student_id', 'student', ['id'], unique=False)
    op.create_index('ix_student_email', 'student', ['email'], unique=1)
    # ### end Alembic commands ###
